### ISSUE TITLE
Error when starting image based on 2.2

### ISSUE THREAD

**Issue by mikeh2020** [aescanero/docker-powerdns-admin-alpine#2]
Updating to the latest docker image aescanero/powerdns-admin:latest results in the following errors. Powerdns-admin fails to start:

  ===> Waiting for powerdns-mariadb MySQL service
Connection to powerdns-mariadb 3306 port [tcp/mysql] succeeded!
Using base prefix '/usr'
New python executable in /opt/pdnsadmin/flask/bin/python3
Not overwriting existing python script /opt/pdnsadmin/flask/bin/python (you must use /opt/pdnsadmin/flask/bin/python3)
Installing wheel...done.
===> DB management
---> Running DB Migration
Usage: flask db migrate [OPTIONS]
Error: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory.
Usage: flask db upgrade [OPTIONS] [REVISION]
Error: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory.
===> Update PDNS API connection info
Connection ok
Connection ok
[2020-06-09 18:27:15 +0000] [23] [INFO] Starting gunicorn 19.7.1
[2020-06-09 18:27:15 +0000] [23] [INFO] Listening at: http://0.0.0.0:9191 (23)
[2020-06-09 18:27:15 +0000] [23] [INFO] Using worker: sync
[2020-06-09 18:27:15 +0000] [25] [INFO] Booting worker with pid: 25
[2020-06-09 18:27:15 +0000] [25] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/lib/python3.7/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3.7/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
ModuleNotFoundError: No module named 'app'
[2020-06-09 18:27:15 +0000] [25] [INFO] Worker exiting (pid: 25)
[2020-06-09 18:27:15 +0000] [23] [INFO] Shutting down: Master
[2020-06-09 18:27:15 +0000] [23] [INFO] Reason: Worker failed to boot.

**Comment by aescanero** [comment]
Fixed flask and python problems, change entrypoint for MariaDB (Alter table could hang MariaDB) and Mysql.
Package is now even smaller.
Tested with docker-compose for now

**Comment by aescanero** [comment]
Also tested in EKS.

**Comment by mikeh2020** [comment]
Confirmed working! Thank you for the quick resolution.
